/**
 * ./src/js/redux/constants
 */

export const SEND_REQUEST = 'SEND_REQUEST';
export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_CLAP = 'SEND_CLAP';
export const REQUEST_FINISHED = 'REQUEST_FINISHED';
export const REQUEST_COMMENT_FINISHED = 'REQUEST_COMMENT_FINISHED';
export const REQUEST_CLAP_FINISHED = 'REQUEST_CLAP_FINISHED';
export const RECIEVE_ARTICLES = 'RECIEVE_ARTICLES';
export const RECIEVE_ARTICLE = 'RECIEVE_ARTICLE';
export const LOGIN_USER = 'LOGIN_USER';
export const RECIEVE_USER_DATA = 'RECIEVE_USER_DATA';
